<?php
declare(strict_types=1);

return [
    'core' => [
        'core',
        'frontend_assets',
        'settings',
        'email_headers',
        'email_settings',
        'email_smtp',
        'email_delivery',
        'email_workflow',
        'options',
        'auth',
        'users',
    ],
    'inventory' => [
        'item_support',
        'item_pages',
        'items',
        'item_actions',
        'item_movements',
        'storage_support',
        'storage_pages',
        'storages',
        'inventory_stock',
        'item_packages',
        'movements',
        'dashboard',
        'scan',
    ],
    'exports' => [
        'export_items',
        'export_movements',
        'export_daily_summary',
        'export_storages',
        'export_workflows',
    ],
    'reports_and_search' => [
        'report_summary',
        'report_presets',
        'notifications',
        'search_helpers',
        'search_reference',
        'search_pages',
        'search_results',
        'search_handlers',
    ],
    'handover_usage' => [
        'handover_usage_reasons',
        'handover_usage_breakdowns',
        'handover_usage_inputs',
        'handover_receipt_updates',
        'handover_closeout_updates',
        'handover_usage_persistence',
        'handover_queries',
        'handover_status',
        'handover_permissions',
    ],
    'workflow_core' => [
        'workflow_system',
        'workflow_inputs',
        'workflow_identity',
        'workflow_stock_impact',
        'workflow_core',
        'workflow_filters',
        'handover_inventory',
        'signoff',
    ],
    'requests' => [
        'request_support',
        'request_pages',
        'request_create',
        'request_decisions',
        'request_receipts',
        'request_status',
        'request_exports',
    ],
    'handovers' => [
        'handover_pages',
        'handover_create',
        'handover_line_edits',
        'handover_request_decisions',
        'handover_cancellations',
        'handover_decisions',
        'handover_receipts',
        'handover_closeout',
    ],
    'purchases_and_ocr' => [
        'ocr_support',
        'ocr_parser',
        'ocr',
        'ocr_openai',
        'purchase_documents',
        'purchase_lookup',
        'purchase_line_inputs',
        'purchase_supplier_persistence',
        'purchase_drafts',
        'purchase_item_creation',
        'purchase_import',
        'purchase_pages',
        'purchase_lifecycle',
        'purchases',
    ],
    'files_and_operations' => [
        'file_library',
        'upload_inputs',
        'purchase_file_uploads',
        'workflow_file_uploads',
        'item_image_uploads',
        'asset_file_uploads',
        'file_asset_meta',
        'file_asset_registry',
        'file_media_settings',
        'stocktakes',
        'suppliers',
        'reorder',
        'audit',
        'labels',
        'documentation_guides',
        'documentation_content',
        'documentation',
    ],
    'assets' => [
        'asset_support',
        'asset_category_support',
        'asset_categories',
        'assets',
        'asset_lifecycle',
        'asset_exports',
        'asset_signoff',
    ],
];
