CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('owner', 'admin', 'staff') NOT NULL DEFAULT 'admin',
    position VARCHAR(80) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    assigned_owner_user_id BIGINT UNSIGNED NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_users_position (position),
    INDEX idx_users_assigned_owner (assigned_owner_user_id),
    CONSTRAINT fk_users_assigned_owner FOREIGN KEY (assigned_owner_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storages (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    system_key VARCHAR(80) NULL,
    storage_type ENUM('warehouse', 'storage') NOT NULL DEFAULT 'storage',
    notes TEXT NULL,
    is_system TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    owner_user_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_storages_system_key (system_key),
    INDEX idx_storages_name (name),
    INDEX idx_storages_system (is_system),
    INDEX idx_storages_status (is_active),
    INDEX idx_storages_owner (owner_user_id),
    CONSTRAINT fk_storages_owner_user FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_storages_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_storages_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    permission_key VARCHAR(120) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uniq_user_permission (user_id, permission_key),
    INDEX idx_user_permissions_key (permission_key),
    CONSTRAINT fk_user_permissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_permissions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(120) PRIMARY KEY,
    setting_value TEXT NULL,
    updated_by BIGINT UNSIGNED NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_app_settings_updated_by (updated_by),
    CONSTRAINT fk_app_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NULL,
    email VARCHAR(190) NOT NULL DEFAULT '',
    ip_address VARCHAR(64) NOT NULL DEFAULT '',
    user_agent VARCHAR(255) NULL,
    success TINYINT(1) NOT NULL DEFAULT 0,
    failure_reason VARCHAR(80) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_login_attempts_email_time (email, created_at),
    INDEX idx_login_attempts_ip_time (ip_address, created_at),
    INDEX idx_login_attempts_user_time (user_id, created_at),
    CONSTRAINT fk_login_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    requested_by_user_id BIGINT UNSIGNED NULL,
    token_hash CHAR(64) NOT NULL,
    request_ip VARCHAR(64) NULL,
    user_agent VARCHAR(255) NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uniq_password_reset_token_hash (token_hash),
    INDEX idx_password_reset_user (user_id, used_at, expires_at),
    INDEX idx_password_reset_requested_by (requested_by_user_id),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_password_reset_tokens_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS email_delivery_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NULL,
    email_type VARCHAR(80) NOT NULL,
    recipient_email VARCHAR(190) NOT NULL,
    recipient_name VARCHAR(190) NULL,
    subject VARCHAR(190) NOT NULL,
    status ENUM('sent', 'failed', 'suppressed') NOT NULL DEFAULT 'suppressed',
    entity_type VARCHAR(80) NULL,
    entity_id BIGINT UNSIGNED NULL,
    error_message VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_email_logs_user (user_id, created_at),
    INDEX idx_email_logs_type (email_type, created_at),
    INDEX idx_email_logs_entity (entity_type, entity_id),
    INDEX idx_email_logs_status (status, created_at),
    CONSTRAINT fk_email_delivery_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS file_assets (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    source_type VARCHAR(60) NOT NULL,
    source_id BIGINT UNSIGNED NULL,
    context_type VARCHAR(60) NULL,
    context_id BIGINT UNSIGNED NULL,
    display_name VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    archive_path VARCHAR(500) NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    file_group VARCHAR(60) NOT NULL DEFAULT 'general',
    uploaded_by BIGINT UNSIGNED NULL,
    deleted_at DATETIME NULL,
    deleted_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_file_assets_path (relative_path),
    INDEX idx_file_assets_source (source_type, source_id),
    INDEX idx_file_assets_context (context_type, context_id),
    INDEX idx_file_assets_group (file_group, created_at),
    INDEX idx_file_assets_uploaded_by (uploaded_by),
    INDEX idx_file_assets_deleted (deleted_at),
    CONSTRAINT fk_file_assets_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_file_assets_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    sku VARCHAR(80) NOT NULL,
    barcode VARCHAR(120) NULL,
    category VARCHAR(120) NULL,
    storage_id BIGINT UNSIGNED NULL,
    unit VARCHAR(40) NOT NULL DEFAULT 'pcs',
    current_quantity DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cost_per_unit DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    image_path VARCHAR(255) NULL,
    notes TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_items_sku (sku),
    INDEX idx_items_barcode (barcode),
    INDEX idx_items_status (is_active),
    INDEX idx_items_category (category),
    INDEX idx_items_storage_id (storage_id),
    CONSTRAINT fk_items_storage FOREIGN KEY (storage_id) REFERENCES storages(id) ON DELETE SET NULL,
    CONSTRAINT fk_items_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_items_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS item_package_presets (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    item_id BIGINT UNSIGNED NOT NULL,
    label VARCHAR(60) NOT NULL,
    pieces_per_unit DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_item_package_label (item_id, label),
    INDEX idx_item_package_default (item_id, is_default),
    INDEX idx_item_package_created_by (created_by),
    INDEX idx_item_package_updated_by (updated_by),
    CONSTRAINT fk_item_package_presets_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_package_presets_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_item_package_presets_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS item_storage_balances (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    item_id BIGINT UNSIGNED NOT NULL,
    storage_id BIGINT UNSIGNED NOT NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_item_storage (item_id, storage_id),
    INDEX idx_item_storage_quantity (storage_id, quantity),
    CONSTRAINT fk_item_storage_balances_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_storage_balances_storage FOREIGN KEY (storage_id) REFERENCES storages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_movements (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    item_id BIGINT UNSIGNED NOT NULL,
    movement_type ENUM('restock', 'usage', 'adjustment', 'transfer') NOT NULL,
    movement_quantity DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_delta DECIMAL(12,2) NOT NULL,
    balance_after DECIMAL(12,2) NOT NULL,
    source_storage_id BIGINT UNSIGNED NULL,
    destination_storage_id BIGINT UNSIGNED NULL,
    source_balance_after DECIMAL(12,2) NULL,
    destination_balance_after DECIMAL(12,2) NULL,
    reference_code VARCHAR(100) NULL,
    context_type VARCHAR(40) NULL,
    context_id BIGINT UNSIGNED NULL,
    notes TEXT NULL,
    used_at DATETIME NOT NULL,
    performed_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_movements_item_date (item_id, used_at),
    INDEX idx_movements_type (movement_type),
    INDEX idx_movements_context (context_type, context_id),
    INDEX idx_movements_source_storage (source_storage_id),
    INDEX idx_movements_destination_storage (destination_storage_id),
    CONSTRAINT fk_movements_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movements_source_storage FOREIGN KEY (source_storage_id) REFERENCES storages(id) ON DELETE SET NULL,
    CONSTRAINT fk_movements_destination_storage FOREIGN KEY (destination_storage_id) REFERENCES storages(id) ON DELETE SET NULL,
    CONSTRAINT fk_movements_user FOREIGN KEY (performed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    actor_user_id BIGINT UNSIGNED NULL,
    notification_type VARCHAR(80) NOT NULL,
    entity_type VARCHAR(40) NULL,
    entity_id BIGINT UNSIGNED NULL,
    title VARCHAR(190) NOT NULL,
    message TEXT NULL,
    action_url VARCHAR(255) NULL,
    read_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_notifications_user (user_id, read_at, created_at),
    INDEX idx_notifications_entity (entity_type, entity_id),
    INDEX idx_notifications_actor (actor_user_id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS item_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_number VARCHAR(40) NOT NULL,
    requester_user_id BIGINT UNSIGNED NOT NULL,
    approver_user_id BIGINT UNSIGNED NOT NULL,
    source_storage_id BIGINT UNSIGNED NOT NULL,
    destination_storage_id BIGINT UNSIGNED NULL,
    request_mode ENUM('issue', 'transfer') NOT NULL DEFAULT 'transfer',
    status ENUM('pending', 'approved', 'receipt_review', 'rejected', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
    needed_by_date DATE NULL,
    notes TEXT NULL,
    decision_notes TEXT NULL,
    receipt_notes TEXT NULL,
    requested_at DATETIME NOT NULL,
    approved_at DATETIME NULL,
    receipt_reported_at DATETIME NULL,
    completed_at DATETIME NULL,
    rejected_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    completed_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_item_requests_number (request_number),
    INDEX idx_item_requests_status (status, requested_at),
    INDEX idx_item_requests_mode (request_mode),
    INDEX idx_item_requests_requester (requester_user_id),
    INDEX idx_item_requests_approver (approver_user_id),
    INDEX idx_item_requests_source_storage (source_storage_id),
    INDEX idx_item_requests_destination_storage (destination_storage_id),
    CONSTRAINT fk_item_requests_requester FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_item_requests_approver FOREIGN KEY (approver_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_item_requests_source_storage FOREIGN KEY (source_storage_id) REFERENCES storages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_item_requests_destination_storage FOREIGN KEY (destination_storage_id) REFERENCES storages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_item_requests_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_item_requests_completed_by FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_item_requests_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS item_request_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    item_name VARCHAR(160) NOT NULL,
    item_sku VARCHAR(80) NOT NULL,
    unit VARCHAR(40) NOT NULL,
    quantity_requested DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_approved DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_received DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_item_request_lines_request (request_id),
    INDEX idx_item_request_lines_item (item_id),
    CONSTRAINT fk_item_request_lines_request FOREIGN KEY (request_id) REFERENCES item_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_request_lines_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS handovers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    handover_number VARCHAR(40) NOT NULL,
    source_storage_id BIGINT UNSIGNED NOT NULL,
    approver_user_id BIGINT UNSIGNED NULL,
    recipient_name VARCHAR(160) NOT NULL,
    recipient_user_id BIGINT UNSIGNED NULL,
    handover_mode ENUM('direct', 'request') NOT NULL DEFAULT 'direct',
    status ENUM('requested', 'awaiting_receipt', 'receipt_review', 'delivered', 'pending_approval', 'closed', 'rejected', 'cancelled') NOT NULL DEFAULT 'delivered',
    scheduled_for_date DATE NULL,
    notes TEXT NULL,
    request_decision_notes TEXT NULL,
    receipt_notes TEXT NULL,
    closed_notes TEXT NULL,
    requested_at DATETIME NULL,
    issued_at DATETIME NOT NULL,
    request_approved_at DATETIME NULL,
    request_rejected_at DATETIME NULL,
    receipt_reported_at DATETIME NULL,
    submitted_at DATETIME NULL,
    approved_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    created_by BIGINT UNSIGNED NULL,
    request_approved_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    approved_by BIGINT UNSIGNED NULL,
    completed_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_handovers_number (handover_number),
    INDEX idx_handovers_status (status, issued_at),
    INDEX idx_handovers_approver (approver_user_id),
    INDEX idx_handovers_mode (handover_mode),
    INDEX idx_handovers_source_storage (source_storage_id),
    INDEX idx_handovers_recipient_user (recipient_user_id),
    CONSTRAINT fk_handovers_source_storage FOREIGN KEY (source_storage_id) REFERENCES storages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_handovers_approver_user FOREIGN KEY (approver_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_recipient_user FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_request_approved_by FOREIGN KEY (request_approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_submitted_by FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_completed_by FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_handovers_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS handover_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    handover_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    item_name VARCHAR(160) NOT NULL,
    item_sku VARCHAR(80) NOT NULL,
    unit VARCHAR(40) NOT NULL,
    quantity_handed DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_received DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_used DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_returned DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_handover_lines_handover (handover_id),
    INDEX idx_handover_lines_item (item_id),
    CONSTRAINT fk_handover_lines_handover FOREIGN KEY (handover_id) REFERENCES handovers(id) ON DELETE CASCADE,
    CONSTRAINT fk_handover_lines_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workflow_documents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workflow_type ENUM('handover', 'request') NOT NULL,
    workflow_id BIGINT UNSIGNED NOT NULL,
    document_type ENUM('proof_image', 'signoff_pdf', 'signoff_excel') NOT NULL DEFAULT 'proof_image',
    stage VARCHAR(80) NOT NULL DEFAULT 'general',
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    uploaded_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_workflow_documents_workflow (workflow_type, workflow_id),
    INDEX idx_workflow_documents_type (document_type, stage),
    INDEX idx_workflow_documents_uploaded_by (uploaded_by),
    CONSTRAINT fk_workflow_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(190) NOT NULL,
    supplier_type ENUM('service', 'product', 'other') NOT NULL DEFAULT 'product',
    supplier_type_other VARCHAR(120) NULL,
    phone VARCHAR(80) NOT NULL DEFAULT '',
    email VARCHAR(190) NULL,
    tax_number VARCHAR(120) NULL,
    commercial_registration VARCHAR(120) NULL,
    national_address VARCHAR(255) NOT NULL DEFAULT '',
    authorized_person VARCHAR(190) NOT NULL DEFAULT '',
    notes TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_suppliers_name (name),
    INDEX idx_suppliers_type (supplier_type),
    INDEX idx_suppliers_status (is_active),
    CONSTRAINT fk_suppliers_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_suppliers_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_number VARCHAR(40) NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    destination_storage_id BIGINT UNSIGNED NOT NULL,
    requester_user_id BIGINT UNSIGNED NOT NULL,
    approver_user_id BIGINT UNSIGNED NOT NULL,
    receiver_user_id BIGINT UNSIGNED NULL,
    status ENUM('draft', 'pending_approval', 'approved', 'receipt_review', 'completed', 'rejected', 'cancelled') NOT NULL DEFAULT 'draft',
    currency VARCHAR(8) NOT NULL DEFAULT 'SAR',
    expected_date DATE NULL,
    notes TEXT NULL,
    decision_notes TEXT NULL,
    receipt_notes TEXT NULL,
    submitted_at DATETIME NULL,
    approved_at DATETIME NULL,
    receipt_reported_at DATETIME NULL,
    completed_at DATETIME NULL,
    rejected_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    completed_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_purchases_number (purchase_number),
    INDEX idx_purchases_status (status, created_at),
    INDEX idx_purchases_supplier (supplier_id),
    INDEX idx_purchases_storage (destination_storage_id),
    INDEX idx_purchases_requester (requester_user_id),
    INDEX idx_purchases_approver (approver_user_id),
    CONSTRAINT fk_purchases_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchases_storage FOREIGN KEY (destination_storage_id) REFERENCES storages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchases_requester FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchases_approver FOREIGN KEY (approver_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchases_receiver FOREIGN KEY (receiver_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchases_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchases_completed_by FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchases_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NULL,
    item_name VARCHAR(160) NOT NULL,
    item_sku VARCHAR(80) NOT NULL,
    item_barcode VARCHAR(120) NULL,
    item_category VARCHAR(120) NULL,
    unit VARCHAR(40) NOT NULL DEFAULT 'pcs',
    item_image_path VARCHAR(255) NULL,
    item_notes TEXT NULL,
    quantity_requested DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_approved DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_received DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    quantity_final DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    unit_cost_quoted DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    unit_cost_approved DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_purchase_lines_purchase (purchase_id),
    INDEX idx_purchase_lines_item (item_id),
    CONSTRAINT fk_purchase_lines_purchase FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_lines_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_documents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_id BIGINT UNSIGNED NOT NULL,
    purchase_line_id BIGINT UNSIGNED NULL,
    document_type ENUM('quote', 'price_list', 'receipt', 'proof', 'other') NOT NULL DEFAULT 'proof',
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    uploaded_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_purchase_documents_purchase (purchase_id),
    INDEX idx_purchase_documents_line (purchase_line_id),
    CONSTRAINT fk_purchase_documents_purchase FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_documents_line FOREIGN KEY (purchase_line_id) REFERENCES purchase_lines(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stocktakes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    stocktake_number VARCHAR(40) NOT NULL,
    storage_id BIGINT UNSIGNED NOT NULL,
    status ENUM('draft', 'pending_approval', 'approved', 'cancelled') NOT NULL DEFAULT 'draft',
    notes TEXT NULL,
    counted_at DATETIME NULL,
    approved_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    created_by BIGINT UNSIGNED NULL,
    approved_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_stocktakes_number (stocktake_number),
    INDEX idx_stocktakes_storage (storage_id),
    INDEX idx_stocktakes_status (status, created_at),
    CONSTRAINT fk_stocktakes_storage FOREIGN KEY (storage_id) REFERENCES storages(id) ON DELETE RESTRICT,
    CONSTRAINT fk_stocktakes_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stocktakes_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stocktakes_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stocktake_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    stocktake_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    item_name VARCHAR(160) NOT NULL,
    item_sku VARCHAR(80) NOT NULL,
    unit VARCHAR(40) NOT NULL,
    expected_quantity DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    counted_quantity DECIMAL(12,2) NULL,
    variance_quantity DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    notes TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_stocktake_lines_stocktake (stocktake_id),
    INDEX idx_stocktake_lines_item (item_id),
    CONSTRAINT fk_stocktake_lines_stocktake FOREIGN KEY (stocktake_id) REFERENCES stocktakes(id) ON DELETE CASCADE,
    CONSTRAINT fk_stocktake_lines_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NULL,
    action VARCHAR(120) NOT NULL,
    entity_type VARCHAR(80) NULL,
    entity_id BIGINT UNSIGNED NULL,
    summary VARCHAR(255) NOT NULL,
    metadata TEXT NULL,
    ip_address VARCHAR(64) NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_activity_user (user_id, created_at),
    INDEX idx_activity_entity (entity_type, entity_id),
    INDEX idx_activity_action (action),
    CONSTRAINT fk_activity_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
